<?php
// Dashboard Market Configuration
// Generated by setup script on 2025-08-27 10:49:49

if (!defined('DB_PATH')) {
    define('DB_PATH', __DIR__ . '/data/dashboardmarket.sqlite');
}
if (!defined('ENVIRONMENT')) {
    define('ENVIRONMENT', 'development');
}
if (!defined('DEBUG_MODE')) {
    define('DEBUG_MODE', true);
}
if (!defined('TIMEZONE')) {
    define('TIMEZONE', 'Asia/Bangkok');
}

// Security settings
if (!defined('SECURE_COOKIES')) {
    define('SECURE_COOKIES', true);
}
if (!defined('SESSION_LIFETIME')) {
    define('SESSION_LIFETIME', 3600); // 1 hour
}

// Set timezone
if (!function_exists('date_default_timezone_set') || date_default_timezone_get() !== TIMEZONE) {
    date_default_timezone_set(TIMEZONE);
}

// Error reporting
if (ENVIRONMENT === 'development') {
    error_reporting(E_ALL);
    ini_set('display_errors', 1);
} else {
    error_reporting(0);
    ini_set('display_errors', 0);
}
